/**
 * Vercel Speed Insights integration for Express API server
 * 
 * Speed Insights is primarily designed for client-side web applications.
 * This utility provides helper functions for integrating Speed Insights
 * if this API server needs to serve HTML pages in the future.
 * 
 * For frontend applications, use the framework-specific packages:
 * - Next.js: @vercel/speed-insights/next
 * - React: @vercel/speed-insights/react
 * - Vue: @vercel/speed-insights/vue
 * - etc.
 * 
 * For this Express API, the script tag approach is used.
 */

/**
 * Returns the Speed Insights script tag that can be injected into HTML responses
 * @returns HTML script tag for Speed Insights
 */
export function getSpeedInsightsScript(): string {
  // The script path is generated by Vercel when Speed Insights is enabled
  // in the Vercel dashboard. This is a placeholder that will work when
  // the project is deployed to Vercel with Speed Insights enabled.
  return '<script defer src="/_vercel/speed-insights/script.js"></script>';
}

/**
 * Middleware to inject Speed Insights into HTML responses
 * This can be used if the API serves HTML pages
 */
export function injectSpeedInsights(html: string): string {
  // Inject the script before the closing </head> tag if it exists,
  // otherwise before the closing </body> tag
  const script = getSpeedInsightsScript();
  
  if (html.includes('</head>')) {
    return html.replace('</head>', `${script}\n</head>`);
  } else if (html.includes('</body>')) {
    return html.replace('</body>', `${script}\n</body>`);
  }
  
  // If neither tag exists, return the HTML as-is
  return html;
}

/**
 * Express middleware to automatically inject Speed Insights into HTML responses
 * Usage: app.use(speedInsightsMiddleware);
 */
export function speedInsightsMiddleware(req: any, res: any, next: any) {
  const originalSend = res.send;
  
  res.send = function (data: any) {
    // Only process HTML responses
    if (typeof data === 'string' && res.get('Content-Type')?.includes('text/html')) {
      data = injectSpeedInsights(data);
    }
    return originalSend.call(this, data);
  };
  
  next();
}
